data:
  data_path: "data/raw"  
  processed_path: "data/processed"
  seq_length: 28
  train_ratio: 0.7
  batch_size: 16
  target_column: "sales"
  item_index: 6780
  lags: [1, 7, 14, 28, 365]
  rolling_windows: [7, 14, 28, 60, 180, 365]
  weekday_embeddings:
    Sunday: [0.4, -0.3, 0.6, 0.1]
    Monday: [0.2, 0.2, 0.5, -0.3]
    Tuesday: [0.1, -1.0, 1.3, 0.9]
    Wednesday: [-0.6, 0.5, 1.2, 0.7]
    Thursday: [0.9, 0.2, -0.1, 0.6]
    Friday: [0.4, 1.1, 0.3, -1.5]
    Saturday: [0.3, -0.2, 0.6, 0.0]
